apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-webhook
spec:
  selector:
    matchLabels:
      app: telegram-webhook
  replicas: 1
  template:
    metadata:
      labels:
        app: telegram-webhook
    spec:
      containers:
      - name: webhook
        image: registry:32000/creator-test:0.3
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: BOOTSTRAP_SERVERS_CONFIG
          value: my-cluster-kafka-bootstrap:9092

