---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - api.[FQDM]
      secretName: api-ingress-tls
  rules:
    - host: api.[FQDM]
      http:
        paths:
          - path: /microbot
            pathType: Prefix
            backend:
              service:
                name: microbot
                port:
                  number: 80
          - path: /debugbot
            pathType: Prefix
            backend:
              service:
                name: nginx-test
                port:
                  number: 80
