apiVersion: apps/v1
kind: Deployment
metadata:
  name: paketo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paketo-builder
  template:
    metadata:
      labels:
        app: paketo-builder
    spec:
      containers:
        - name: paketo-builder
          image: paketobuildpacks/builder
          command:
            - "/bin/sh"
            - "-c"
            - |
              git clone https://github.com/bthode/telegram-webhook.git
              /cnb/lifecycle/creator -app=telegram-webhook/ registry:32000/creator-test:0.1
          ports:
          volumeMounts:
            - name: docker-daemon-volume
              mountPath: /etc/docker
            - name: docker-config
              mountPath: /home/cnb/.docker
      volumes:
        - name: docker-daemon-volume
          configMap:
            name: docker-configmap
            items:
              - key: daemon.json
                path: daemon.json
        - name: docker-config
          configMap:
            name: docker-configmap
            items:
              - key: config.json
                path: config.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-configmap
data:
  daemon.json: |
    {
      "insecure-registries": ["registry:32000"],
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "10m",
        "max-file": "3"
      }
    }
  config.json: |
    {
        "auths": {
            "registry:32000/": {
                "auth": ""
            }
        }
    }
